database:
  driver: mysql
  connection: 
  logger:
    # kafka:
        #   brokers:
        #     - steamer-01.srvs.cloudkafka.com:9093
        #     - steamer-02.srvs.cloudkafka.com:9093
        #     - steamer-03.srvs.cloudkafka.com:9093
        #   topic: labs
  behaviorLog:
     kafka:
        # brokers:
        #   - steamer-01.srvs.cloudkafka.com:9093
        #   - steamer-02.srvs.cloudkafka.com:9093
        #   - steamer-03.srvs.cloudkafka.com:9093
        # topic: labs
debug: true
service: bmapping-api
httpport: 8080